package com.hylamobile.promotion.enums;

/**
 * @author XHe
 */
public enum CategoryQuestionCode{
    QUANTITY, REF_NO,
    // REF_NO

    CELL_PHONE_IMEI_ESN,
    // CELL_PHONE_IMEI_ESN,
    // TABLET_IMEI_ESN

    POWER_ON,
    // CELL_PHONE_POWER_UP_DROPDOWN,
    // CELL_PHONE_POWER_UP_DROPDOWN_1,
    // CELL_PHONE_POWER_UP_DROPDOWN_2,
    // CELL_PHONE_POWER_UP_DROPDOWN_ALT,
    // CELL_PHONE_POWER_UP_DROPDOWN_3,
    // CELL_PHONE_UNIT_POWER_UP_DROPDOWN,
    // TABLET_POWER_UP_DROPDOWN,
    // TABLET_POWER_UP_DROPDOWN_1,
    // TABLET_POWER_UP_DROPDOWN_2,

    // IMPORTANT NOTE:----------- for OFR TABLET_FUNCTIONALITY_DROPDOWN = LCD_FUNCTIONALITY in DB

    ACCESSORIES,
    // CELL_PHONE_ACCESSORIES_CHECKBOX,
    // CELL_PHONE_ACCESSORIES_CHECKBOX_1,
    // CELL_PHONE_INVOICE_ACCESSORIES,

    COLOR,
    // CELL_PHONE_COLOR_TEXT, No ref
    // CELL_PHONE_COLOR,

    CARRIER,
    // CELL_PHONE_CARRIER_DROPDOWN,

    BAD_CHARGER_PORT,
    // CELL_PHONE_BAD_CHARGER_PORT,

    USER_LOCKED,
    // CELL_PHONE_USER_LOCKED,

    BAD_SOFTWARE,
    // CELL_PHONE_BAD_SOFTWARE,

    BAD_IMEI_ESN,
    // CELL_PHONE_BAD_IMEI_ESN,

    WATER_STICKER_TAMPERED,
    // CELL_PHONE_WATER_STICKER_TAMPERED,

    DATA_CLEARED,
    // CELL_PHONE_DATA_CLEARED

    TEST_CALL,
    // CELL_PHONE_TEST_CALL_DROPDOWN

    SPEAKER_CONDITION,
    // CELL_PHONE_SPEAKER_CONDITION_DROPDOWN

    DATA_PORT,
    // CELL_PHONE_DATA_PORT_DROPDOWN

    WATER_DAMAGE,
    // CELL_PHONE_WATER_DAMAGE,
    // CELL_PHONE_WATER_DAMAGE_1,

    DAMAGE, NO_SCREEN_DAMAGE, // specific for screen damage
    NO_DAMAGE, // IMPORTANT NOTE:---------- For Verizon CELL_PHONE_DAMAGE_DROPDOWN_2 = NO_DAMAGE
    // CELL_PHONE_DAMAGE_DROPDOWN_ALT,
    // CELL_PHONE_DAMAGE_DROPDOWN_1,
    // CELL_PHONE_DAMAGE_DROPDOWN_2,
    // TABLET_DAMAGE_DROPDOWN,
    // CELL_PHONE_DISPLAY_DROPDOWN, -- did not find any reference in DB otherwise in code opposite response in
    // itemdetail.hasDamage()
    // CELL_PHONE_BROKEN_DROPDOWN, -- Broken is used in sprint there are multiple questions in DB using active 2
    // codes as BROKEN and DAMAGE
    // CELL_PHONE_DAMAGE_DROPDOWN_POSTINSPECTION,
    // CELL_PHONE_DAMAGE_DROPDOWN

    CUSTOMER_NAME,
    // CELL_PHONE_CUSTOMER_NAME

    CELL_PHONE_PHONE_NUM,
    // CELL_PHONE_PHONE_NUM

    ACCOUNT_NO,
    // CELL_PHONE_ACCOUNT_NO,
    // CELL_PHONE_INVOICE_ACCOUNT_NO,

    CONDITION_RATING, LIKE_NEW,
    // CELL_PHONE_CONDITION_RATING,
    // CELL_PHONE_CONDITION_RATING_NEW,
    // TABLET_CONDITION_RATING_NEW,
    // CONSUMER_ELECTRONICS_CONDITION_RATING, ---------- no ref in code and DB

    SCREEN_CONDITION_RATING,
    // CELL_PHONE_SCREEN_CONDITION_RATING_3
    BODY_CONDITION_RATING,
    // CELL_PHONE_BODY_CONDITION_RATING_3

    LCD_FUNCTIONALITY,
    // CELL_PHONE_LCD_FUNCTIONALITY_DROPDOWN,
    // CELL_PHONE_DISPLAY_FUNCTIONALITY_DROPDOWN,
    // CELL_PHONE_LCD_FUNCTIONALITY_DROPDOWN_1,
    // CELL_PHONE_FUNCTIONALITY_DROPDOWN, --no ref in DB and Code

    BATTERY_MISSING, BATTERY_PRESENT, BATTERY_DAMAGE,
    // CELL_PHONE_BATTERY_MISSING
    // CELL_PHONE_BATTERY_DROPDOWN -------- no ref in code but in DB
    // CELL_PHONE_BATTERY
    // CELL_PHONE_BATTERY_MISSING_1,
    // CELL_PHONE_BATTERY_MISSING_2,
    // IMPORTANT NOTE:---------- For Verizon CELL_PHONE_BATTERY_MISSING_2 = BATTERY_PRESENT

    CUSTOMER_FIRST_NAME,
    // CELL_PHONE_INVOICE_CUSTOMER_FIRST_NAME
    // CELL_PHONE_CUSTOMER_FIRST_NAME

    CUSTOMER_LAST_NAME,
    // CELL_PHONE_INVOICE_CUSTOMER_LAST_NAME
    // CELL_PHONE_CUSTOMER_LAST_NAME

    CUSTOMER_TITLE,
    // CELL_PHONE_INVOICE_CUSTOMER_TITLE

    BANK_CODE,
    // CELL_PHONE_INVOICE_BANK_CODE

    ACCOUNT_HOLDER_NAME,
    // CELL_PHONE_INVOICE_ACCOUNT_HOLDER_NAME

    STREET,
    // CELL_PHONE_INVOICE_STREET
    // CELL_PHONE_INVOICE_STREET_NUMBER,

    HOUSE_NO,
    // CELL_PHONE_INVOICE_HOUSE_NO

    CITY,
    // CELL_PHONE_INVOICE_CITY

    POSTAL_CODE,
    // CELL_PHONE_INVOICE_POSTAL_CODE

    EMAIL,
    // CELL_PHONE_INVOICE_EMAIL

    STORE_EMPLOYEE_NAME,
    // CELL_PHONE_INVOICE_STORE_EMPLOYEE_NAME

    NEW_PHONE_NUM,
    // CELL_PHONE_INVOICE_NEW_PHONE_NUM

    NEW_IMEI_NUM,
    // CELL_PHONE_INVOICE_NEW_IMEI_NUM
    // CELL_PHONE_INVOICE_PHONE_IMEI_CODE

    PERSONAL_TAX_CODE,
    // CELL_PHONE_INVOICE_PERSONAL_TAX_CODE

    CUSTOMER_STATUS,
    // CELL_PHONE_INVOICE_CUSTOMER_STATUS

    CUSTOMER_COUNTRY,
    // CELL_PHONE_INVOICE_CUSTOMER_COUNTRY

    GIFT_CARD,
    // CELL_PHONE_INVOICE_GIFT_CARD

    SIM_SERIAL_NUMBER,
    // CELL_PHONE_INVOICE_SIM_SERIAL_NUMBER
    // CELL_PHONE_INVOICE_SIM_CARD_SERIAL_NUMBER, only in demo and erc side

    TOP_UP,
    // CELL_PHONE_INVOICE_TOP_UP

    IDENTITY_DOC_TYPE,
    // CELL_PHONE_INVOICE_IDENTITY_DOC_TYPE

    IDENTITY_DOC_NUMBER,
    // CELL_PHONE_INVOICE_IDENTITY_DOC_NUMBER

    DOC_DELIVERY_AUTHORITY,
    // CELL_PHONE_INVOICE_IDENTITY_DOC_DELIVERY_AUTHORITY

    DOC_DELIVERY_DATE,
    // CELL_PHONE_INVOICE_IDENTITY_DOC_DELIVERY_DATE

    DOC_CONFIRM_OF_COPY,
    // CELL_PHONE_INVOICE_IDENTITY_DOC_CONFIRM_OF_COPY

    COMMENT,
    // CELL_PHONE_INVOICE_COMMENT

    TRANSACTION_TYPE,
    // CELL_PHONE_INVOICE_TRANSACTION_TYPE

    SMARTPASS_NUMBER,
    // CELL_PHONE_INVOICE_SMARTPASS_NUMBER

    STATE,
    // CELL_PHONE_INVOICE_STATE

    CHARGER_INCLUDED,
    // TABLET_ADAPTER_INCLUDED_DROPDOWN,

    DEACTIVATED,
    // CELL_PHONE_FIND_IPHONE_TURNED_OFF

    OTHER_DEVICES,

    CODE_SCRATCH_CARD,

    SEGMENT,

    PRO_COMPANY_NAME,

    PRO_COMPANY_ID_NUMBER,

    PRO_COMPANY_DOCUMENT_PRESENT,

    PRO_CUSTOMER_FUNCTION, INVOICE_NUMBER,

    IDENTITY_DOC_EXP_DATE,
    // Below question added for requirement BCE-8 to reduce price to $0 for activated lock
    HIDDEN_ZERO_VALUE,

    CUSTOMER_FIRST_NAME_DEALER,

    CUSTOMER_LAST_NAME_DEALER,

    CUSTOMER_BILLING_PHONE_NUMBER,

    ACCOUNT_NUMBER,

    SUB_ACCOUNT_NUMBER,

    MEMORY_SIZE,
    STREET_2,
    RIGHT_TO_TRADE,
    WORK_PHONE,
    HEIGHT_FEET,
    RACE,
    WEIGHT,
    COUNTRY_ORIGIN,
    PROVINCE,
    HEIGHT_INCHES,
    NO_UNDER_INFLUENCE,
    GENDER,
    ID_NUMBER,
    CUSTOMER_MIDDLE_NAME,
    EYE_COLOR,
    HOME_PHONE,
    IDENTIFYING_MARKS,
    ID_TYPE,
    DEVICE_COLOR,
    WORKPLACE,
    FCC_CODE,
    DOB,
    NETWORK_SIGNAL,
    HAIR_COLOR
}
