package com.hylamobile.promotion.enums;

public enum ProcessName {
    WAREHOUSE_MIGRATION("FAILED_BACK_MIGRATION_ITEM"), PAID_ITEM_NOTIFICATION("PAID_ITEM"), INSPECTED_ITEM_NOTIFICATION(
            "INSPECTED_ITEM"), META_DATA_MIGRATION_ID("META_DATA_FRONT_MIGRATION"), CARTON_BACK_MIGRATION(
            "FAILED_CARTON_BACK_MIGRATION"), FAILED_FRONT_MIGRATION_INVOICE("FAILED_FRONT_MIGRATION_INVOICE"), FAILED_FRONT_MIGRATION_CARTON(
            "FAILED_FRONT_MIGRATION_CARTON"), FAILED_PRE_NOTIFICATION_RECEIPT_JOB(
            "FAILED_PRE_NOTIFICATION_RECEIPT_JOB"), FAILED_B2B_QUOTES("FAILED_B2B_QUOTES"), CLOSE_ITEM_MIGRATION(
            "CLOSE_ITEM_MIGRATION"),
    FAILED_TRADE_MOVEMENT("FAILED_TRADE_MOVEMENT"),
    INITIAL_RECEIVED_INFORMATION_MIGRATION("INITIAL_RECEIVED_INFORMATION_MIGRATION"),
    // PROD-70
    POST_REMARK("POST_REMARK"),
    // PROD-268
    SPO_MAINTENANCE("SPO_MAINTENANCE"),
    RETRIEVE_OFFERS("RETRIEVE_OFFERS"),
    LOAN_STATUSES("LOAN_STATUSES"), BUY_GET_LOAN_CREATE("BUY_GET_LOAN_CREATE"),
    UPGRADE_REASON("UPGRADE_REASON"), EXTERNAL_SHIPMENT_TRACK("EXTERNAL_SHIPMENT_TRACK"),
    EVALUATE_TRADE("EVALUATE_TRADE"), UPDATE_TRADE("UPDATE_TRADE"),
    FAILED_B2B_INVOICE_MIGRATION(
            "FAILED_B2B_INVOICE_MIGRATION"), HOLD_INFORMATION_MIGRATION("HOLD_INFORMATION_MIGRATION"),
    MARK_ITEM_PAID_FAILED("MARK_ITEM_PAID_FAILED"), EQUIPMENT_PROMISED_VALUE("EQUIPMENT_PROMISED_VALUE"),
    ZIP_FLOW_TRADE("ZIP_FLOW_TRADE"),
    ATT_ZIP_ORDER_DETAILS("ATT_ZIP_ORDER_DETAILS"), GENERATE_RECEIPT("GENERATE_RECEIPT"), UPLOAD_SIGNATURE_TO_S3("UPLOAD_SIGNATURE_TO_S3"),
    PROMOTION_CREDIT_MAINTENANCE("PROMOTION_CREDIT_MAINTENANCE"), FAILED_SIGNED_RECEIPT_JOB_FAILED("FAILED_SIGNED_RECEIPT_JOB_FAILED");

    private final String process;

    public String getProcess() {
        return this.process;
    }

    private ProcessName(String process) {
        this.process = process;
    }
}
